#############################################################################
# Makefile for building: savescr
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? ???? 25 23:51:57 2011
# Project:  savescr.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile savescr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		screenshotarea.cpp \
		screeneditor.cpp \
		rwidget.cpp \
		qcolorpicker.cpp \
		imagelistwidgetitem.cpp moc_mainwindow.cpp \
		moc_screenshotarea.cpp \
		moc_screeneditor.cpp \
		moc_rwidget.cpp \
		moc_qcolorpicker.cpp
OBJECTS       = main.o \
		mainwindow.o \
		screenshotarea.o \
		screeneditor.o \
		rwidget.o \
		qcolorpicker.o \
		imagelistwidgetitem.o \
		moc_mainwindow.o \
		moc_screenshotarea.o \
		moc_screeneditor.o \
		moc_rwidget.o \
		moc_qcolorpicker.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		savescr.pro
QMAKE_TARGET  = savescr
DESTDIR       = 
TARGET        = savescr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_screenshotarea.h ui_screeneditor.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: savescr.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile savescr.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile savescr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/savescr1.0.0 || $(MKDIR) .tmp/savescr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/savescr1.0.0/ && $(COPY_FILE) --parents mainwindow.h screenshotarea.h screeneditor.h rwidget.h qcolorpicker.h imagelistwidgetitem.h .tmp/savescr1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp screenshotarea.cpp screeneditor.cpp rwidget.cpp qcolorpicker.cpp imagelistwidgetitem.cpp .tmp/savescr1.0.0/ && $(COPY_FILE) --parents mainwindow.ui screenshotarea.ui screeneditor.ui .tmp/savescr1.0.0/ && (cd `dirname .tmp/savescr1.0.0` && $(TAR) savescr1.0.0.tar savescr1.0.0 && $(COMPRESS) savescr1.0.0.tar) && $(MOVE) `dirname .tmp/savescr1.0.0`/savescr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/savescr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_screenshotarea.cpp moc_screeneditor.cpp moc_rwidget.cpp moc_qcolorpicker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_screenshotarea.cpp moc_screeneditor.cpp moc_rwidget.cpp moc_qcolorpicker.cpp
moc_mainwindow.cpp: screenshotarea.h \
		screeneditor.h \
		rwidget.h \
		imagelistwidgetitem.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_screenshotarea.cpp: screenshotarea.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) screenshotarea.h -o moc_screenshotarea.cpp

moc_screeneditor.cpp: rwidget.h \
		imagelistwidgetitem.h \
		screeneditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) screeneditor.h -o moc_screeneditor.cpp

moc_rwidget.cpp: rwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rwidget.h -o moc_rwidget.cpp

moc_qcolorpicker.cpp: qcolorpicker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcolorpicker.h -o moc_qcolorpicker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_screenshotarea.h ui_screeneditor.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_screenshotarea.h ui_screeneditor.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_screenshotarea.h: screenshotarea.ui
	/usr/bin/uic-qt4 screenshotarea.ui -o ui_screenshotarea.h

ui_screeneditor.h: screeneditor.ui \
		qcolorpicker.h
	/usr/bin/uic-qt4 screeneditor.ui -o ui_screeneditor.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		screenshotarea.h \
		screeneditor.h \
		rwidget.h \
		imagelistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		screenshotarea.h \
		screeneditor.h \
		rwidget.h \
		imagelistwidgetitem.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

screenshotarea.o: screenshotarea.cpp screenshotarea.h \
		ui_screenshotarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screenshotarea.o screenshotarea.cpp

screeneditor.o: screeneditor.cpp screeneditor.h \
		rwidget.h \
		imagelistwidgetitem.h \
		ui_screeneditor.h \
		qcolorpicker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screeneditor.o screeneditor.cpp

rwidget.o: rwidget.cpp rwidget.h \
		screeneditor.h \
		imagelistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rwidget.o rwidget.cpp

qcolorpicker.o: qcolorpicker.cpp qcolorpicker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcolorpicker.o qcolorpicker.cpp

imagelistwidgetitem.o: imagelistwidgetitem.cpp imagelistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagelistwidgetitem.o imagelistwidgetitem.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_screenshotarea.o: moc_screenshotarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screenshotarea.o moc_screenshotarea.cpp

moc_screeneditor.o: moc_screeneditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screeneditor.o moc_screeneditor.cpp

moc_rwidget.o: moc_rwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rwidget.o moc_rwidget.cpp

moc_qcolorpicker.o: moc_qcolorpicker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcolorpicker.o moc_qcolorpicker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

